import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appName': 'Sports Academy System',
      'workspace': 'Workspace',
      'workspacesTitle': 'Workspaces',
      'basicSection': 'Basic',
      'managementSection': 'Management',
      'switchWorkspace': 'Switch Workspace',
      'createAcademy': 'Create Academy',
      'academyName': 'Academy Name',
      'academyType': 'Academy Type',
      'sport': 'Sport',
      'logo': 'Academy Logo',
      'branchesAndGroups': 'Branches & Groups',
      'profile': 'Profile',
      'invitations': 'Invitations',
      'pendingInvitationsTitle': 'Pending Invitations',
      'players': 'Players',
      'publicPlayersList': 'Public Players List',
      'manageAllPlayersTitle': 'Manage All Players',
      'packagesAndSubscriptions': 'Packages & Subscriptions',
      'choosePackageTitle': 'Choose Academy Package',
      'choosePackageDesc': 'Choose your academy package (Free / Pro)',
      'userManagement': 'User Management',
      'noUsersRegistered': 'No users registered',
      'activityLog': 'Academy Activity Log',
      'activityLogDesc': 'Academy activity and operations log',
      'subscriptionReports': 'Subscription Reports',
      'otherRevenueReport': 'Other Revenue Report',
      'employeeAttendanceAndSalaries': 'Employee Attendance & Salaries',
      'otherExpenses': 'Other Expenses',
      'deleteAccount': 'Delete Account',
      'logout': 'Logout',
      'language': 'Language',
      'changeLanguage': 'Change Language',
      'aboutApp': 'About Application',
      'aboutAppAndPolicies': 'About App & Policies',
      'aboutAppPlaceholderDesc': 'Privacy Policy & Terms & Conditions',
      'noBranchesYet': 'No branches yet',
      'addBranch': 'Add Branch',
      'noPendingInvitations': 'No pending invitations',
      'inviteUser': 'Invite User',
      'noPlayersRegistered': 'No players registered',
      'addPlayer': 'Add Player',
      'searchPlayers': 'Search players...',
      'currentSubscription': 'Current Subscription',
      'freePlan': 'Free Plan',
      'upgrade': 'Upgrade',
      'normalUser': 'Normal User',
      'administrator': 'Administrator / Manager',
      'saveChanges': 'Save Changes',
      'editProfile': 'Edit Profile',
      'changePassword': 'Change Password',
      'oldPassword': 'Current Password',
      'newPassword': 'New Password',
      'confirmPassword': 'Confirm Password',
      'confirmChange': 'Confirm Change',
      'deleteConfirmationTitle': 'Delete Account?',
      'deleteConfirmationDesc': 'This is a destructive action and cannot be undone. Are you sure you want to permanently delete your account?',
      'cancel': 'Cancel',
      'confirmDelete': 'Delete Permanently',
      'privacyPolicy': 'Privacy Policy',
      'termsAndConditions': 'Terms & Conditions',
      'contactUs': 'Contact Us',
      'version': 'Version',
      'noRevenueRecords': 'No revenue records',
      'noExpenses': 'No expenses recorded',
      'noEmployees': 'No employees',
      'noActivity': 'No activity logged',
      'role': 'Role',
      'actions': 'Actions',
      'status': 'Status',
      'date': 'Date',
      'amount': 'Amount',
      'category': 'Category',
      'categoryExampleHint': 'Category (e.g. Maintenance, Equipment)',
      'attendance': 'Attendance',
      'salaries': 'Salaries',
      'present': 'Present',
      'absent': 'Absent',
      'late': 'Late',
      'leave': 'On Leave',
      // Players screen
      'manageSubscribersAndSports': 'Manage Subscribers & Sports',
      'noSubscribersYet': 'No subscribers yet',
      'expiresOn': 'Expires on',
      'currency': 'EGP',
      'addNewSubscriptionTitle': 'Add New Subscription',
      'subscriberName': 'Subscriber Name',
      'sportExampleHint': 'Sport (e.g. Football)',
      'subscriptionAmount': 'Subscription Amount',
      'addAndSave': 'Add & Save',
      'general': 'General',
      // Expenses screen
      'financeAndExpensesManagement': 'Finance & Expenses Management',
      'income': 'Income',
      'expenses': 'Expenses',
      'netBalance': 'Net Balance',
      'noTransactionsRecorded': 'No transactions recorded',
      'addNewTransaction': 'Add New Transaction',
      'descriptionLabel': 'Description',
      'transactionType': 'Transaction Type:',
      'incomeType': 'Income',
      'expenseType': 'Expense',
      'save': 'Save',
      // Profile screen
      'fullName': 'Full Name',
      'phoneNumber': 'Phone Number',
      'nameRequired': 'Name is required',
      'phoneRequired': 'Phone number is required',
      'phoneIncomplete': 'Phone number is incomplete',
      'academyNameRequired': 'Academy name is required',
      'profileSavedSuccess': 'Changes saved successfully',
      'avatarChangeComingSoon': 'Changing profile photo coming soon',
      'requiredField': 'Required',
      'minSixChars': 'Must be at least 6 characters',
      'passwordsMismatch': 'Passwords do not match',
      'passwordChangedSuccess': 'Password changed successfully',
      'genericError': 'Something went wrong, please try again',
      'sportFootball': 'Football',
      'sportBasketball': 'Basketball',
      'sportVolleyball': 'Volleyball',
      'sportSwimming': 'Swimming',
      'sportTennis': 'Tennis',
      'sportOther': 'Other',
      'notLoggedIn': 'Not logged in',
      // Workspace switcher
      'noAcademyNameYet': 'No academy name yet',
      'chooseWorkspace': 'Choose a workspace',
      'noOtherAccountsOnDevice': 'No other accounts registered on this device',
      'switchedTo': 'Switched to',
      'projectManager': 'Project Manager',
      'member': 'Member',
      // Auth screens
      'welcomeBack': 'Welcome Back',
      'loginSubtitle': 'Log in to manage your sports academy',
      'emailLabel': 'Email',
      'passwordLabel': 'Password',
      'enterEmail': 'Please enter your email',
      'invalidEmailFormat': 'Invalid email format',
      'enterPassword': 'Please enter your password',
      'passwordMinLength': 'Password must be at least 6 characters',
      'forgotPassword': 'Forgot password?',
      'contactSupportForPassword': 'Please contact support to recover your password',
      'resetPasswordTitle': 'Reset your password',
      'resetPasswordDesc': "Enter your account's email and we'll send you a link to reset your password.",
      'sendResetLink': 'Send reset link',
      'resetLinkSentTitle': 'Check your inbox',
      'resetLinkSentDesc': "We've sent a password reset link to your email. Open it and follow the instructions to set a new password.",
      'backToLogin': 'Back to login',
      'tooManyRequests': 'Too many attempts, please try again later',
      'networkError': 'Network error, please check your connection',
      'accountDisabled': 'This account has been disabled',
      'verifyEmailBanner': 'Please verify your email address',
      'verifyEmailBannerDesc': "We've sent a verification link to your email.",
      'resendVerificationEmail': 'Resend verification email',
      'verificationEmailSent': 'Verification email sent',
      'iVerifiedRefresh': "I've verified, refresh",
      'loginButton': 'Log In',
      'or': 'Or',
      'noAccountYet': "Don't have an account?",
      'createNewAccount': 'Create New Account',
      'registerSubtitle': 'Join now and start managing your sports academy',
      'enterFullName': 'Enter your full name',
      'enterName': 'Please enter your name',
      'nameTooShort': 'Name is too short',
      'confirmPasswordRequired': 'Please confirm your password',
      'createAccountButton': 'Create Account',
      'alreadyHaveAccount': 'Already have an account?',
      'iAmManager': 'I am a manager / admin',
      'managerAccessCode': 'Manager Access Code',
      'managerAccessCodeHint': 'Enter the manager activation code',
      'managerCodeRequired': 'Please enter the manager activation code',
      'managerRoleHint': "Ask your academy admin for this code if you don't have it",
      // Branches
      'addBranchTitle': 'Add New Branch',
      'branchName': 'Branch Name',
      'branchNameRequired': 'Branch name is required',
      'branchAddress': 'Address (optional)',
      'branchAdded': 'Branch added successfully',
      'deleteBranchConfirm': 'Delete this branch?',
      'managersOnlyHint': 'Only the academy manager can add branches',
      // Packages screen
      'choosePackageHeading': 'Choose Academy Package',
      'choosePackageSubheading': 'Several options to fit your needs',
      'current': 'Current',
      'free': 'Free',
      'proPackage': 'Pro Package',
      'suitableForMediumAcademies': 'Suitable for medium-sized academies',
      'perMonth': '/ month',
      'currentSubscriptionButton': 'Your Current Subscription',
      'subscribeNow': 'Subscribe Now',
      'oneBranch': '1 Branch',
      'twoGroups': '2 Groups',
      'upTo50Players': 'Up to 50 Players',
      'upTo50Reports': 'Up to 50 Reports',
      'twoBranches': '2 Branches',
      'upTo10Groups': 'Up to 10 Groups',
      'upTo200Players': 'Up to 200 Players',
      'upTo200ReportsMonthly': 'Up to 200 Reports monthly',
      'prioritySupport': 'Priority Support',
      'comingSoonFeature': 'Coming soon',
      // About app content
      'aboutAppBody': 'Sports Academy Management System helps academy owners and coaches manage branches, players, subscriptions, finances and staff from one place — simply and efficiently.',
      'ourFeatures': 'Features',
      'featureBranches': 'Manage multiple branches and groups',
      'featurePlayers': 'Full player and subscriber database',
      'featureFinance': 'Track income, expenses and reports',
      'featureAttendance': 'QR-code based attendance check-in',
      'featureTeam': 'Manage staff roles and permissions',
      'developedBy': 'Developed with care for sports academies',
      // Players search / sort / attendance
      'searchByPlayerName': 'Search for a player',
      'sortByName': 'Sort by Name',
      'printList': 'Print List',
      'printPreviewTitle': 'Player List Preview',
      'copyText': 'Copy',
      'textCopied': 'Copied to clipboard',
      'scanAttendance': 'Scan Attendance',
      'showQrCode': 'Show QR Code',
      'playerQrCode': 'Player QR Code',
      'close': 'Close',
      'pointCameraAtCode': 'Point the camera at the player\'s QR code',
      'attendanceRecorded': 'Attendance recorded for',
      'alreadyCheckedInToday': 'already checked in today',
      'codeNotRecognized': 'Code not recognized — this player is not registered',
      'manualCodeEntry': 'Or enter the code manually',
      'submitCode': 'Submit',
      // Role selection at registration
      'accountType': 'Account Type',
      'roleManager': 'Manager',
      'roleEmployee': 'Employee',
      'roleCoach': 'Trainee (Normal)',
      'roleManagerDesc': 'Full access + records employee attendance',
      'roleEmployeeDesc': 'Normal access + can scan trainee attendance',
      'roleCoachDesc': 'Normal access',
      // Employee attendance (recorded by manager)
      'employeeAttendanceTitle': 'Employee Attendance',
      'scanEmployeeAttendance': 'Scan Employee Attendance',
      'noEmployeesRegisteredYet': 'No employees registered yet',
      'checkedInToday': 'Checked in today',
      'notCheckedInToday': 'Not checked in today',
      'pointCameraAtEmployeeCode': "Point the camera at the employee's QR code",
      'employeeNotRecognized': 'Code not recognized — this employee is not registered',
      'myQrCode': 'My QR Code',
      'myQrCodeHint': 'Show this code to be checked in',
      // About / contact / legal
      'editContactNumber': 'Edit Contact Number',
      'contactNumberLabel': 'Contact Number',
      'contactNumberSaved': 'Contact number updated',
      'termsAndConditionsTitle': 'Terms & Conditions',
      'privacyPolicyTitle': 'Privacy Policy',
      'contactUsTitle': 'Contact Us',
      'toggleTheme': 'Switch Light / Dark Mode',
      'lightDarkMode': 'Light / Dark Mode',
      'darkModeLabel': 'Dark Mode',
      'lightModeLabel': 'Light Mode',
      // Invitations
      'sendInvitationTitle': 'Send Invitation',
      'invitationEmailHint': "Invitee's email address",
      'inviteeRoleLabel': 'Invitee Role',
      'invitationSentSuccess': 'Invitation sent successfully',
      'invitationsManagersOnlyHint': 'Only the academy manager can send invitations',
      'invitedAsHint': 'This email is invited to join as',
      'sentOnLabel': 'Sent on',
      // Auth error messages
      'enterValidEmail': 'Please enter a valid email',
      'noAccountWithEmail': 'No account is registered with this email',
      'incorrectPassword': 'Incorrect password',
      'emailAlreadyRegistered': 'This email is already registered, try logging in',
      'invalidManagerCode': 'Invalid manager activation code',
      'incorrectCurrentPassword': 'Current password is incorrect',
      // Manager subscription management
      'manageSubscriptionsTitle': 'Manage Subscriptions',
      'manageSubscriptionsDesc': 'Search a user by email and create or review their subscription',
      'searchUserByEmailLabel': 'Search User by Email',
      'searchUserByEmailHint': 'user@gmail.com',
      'searchButton': 'Search',
      'userNotFoundMsg': 'No user found with this email',
      'selectedUserLabel': 'Selected User',
      'subscriptionDurationLabel': 'Duration',
      'duration1Month': '1 Month',
      'duration3Months': '3 Months',
      'duration6Months': '6 Months',
      'duration1Year': '1 Year',
      'amountPaidLabel': 'Amount Paid',
      'amountPaidHint': 'Enter amount',
      'expiryDatePreviewLabel': 'Expiry Date',
      'createSubscriptionButton': 'Create Subscription',
      'subscriptionCreatedSuccess': 'Subscription created successfully',
      'subscriptionCreationFailed': 'Failed to create subscription',
      'subscriptionHistoryTitle': 'Subscription History',
      'noSubscriptionHistory': 'No subscription history yet',
      'statusActive': 'Active',
      'statusExpired': 'Expired',
      'mySubscriptionTitle': 'My Subscription',
      'noActiveSubscriptionMsg': 'You have no subscription yet',
      'contactAdminToRenewMsg': 'Please contact the administration to activate or renew your subscription.',
      'startDateLabel': 'Start Date',
      'expiryDateLabel': 'Expiry Date',
      'amountPaidColumnLabel': 'Amount Paid',
      'pleaseEnterValidAmount': 'Please enter a valid amount',
      'pleaseSearchUserFirst': 'Please search and select a user first',
      'football': 'Football',
      'manageButton': 'Manage',
      'viewButton': 'View',
      'noSubscriptionShort': 'No Subscription',
      'currentRoleLabel': 'Current Role',
      'promoteToEmployeeButton': 'Promote to Employee',
      'revertToUserButton': 'Revert to User',
      'roleUpdatedSuccess': 'Role updated successfully',
      'roleUpdateFailed': 'Failed to update role',
      'avatarUploadCorsError': 'Upload failed: the file could not be verified after upload. This usually means CORS is not configured on the Firebase Storage bucket for this web app — ask your developer to run "firebase storage:cors" setup, or try again from the mobile app.',
      'avatarUploadPermissionError': 'You do not have permission to upload this image.',
      'avatarUploadGenericError': 'Failed to upload the image. Please try again.',
      'performedByLabel': 'Performed by',
      'searchUsersHint': 'Search by name, email, or phone',
      'noUsersFound': 'No users found',
      'totalRevenueLabel': 'Total Revenue',
      'revenueByCategoryLabel': 'Revenue by Category',
      'revenueTransactionsLabel': 'Revenue Transactions',
      'nationalIdLabel': 'National ID',
      'nationalIdHint': '14-digit National ID',
      'nationalIdInvalid': 'National ID must be 14 digits',
      'copiedToClipboard': 'Copied to clipboard',
      'copyCode': 'Copy Code',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'categoryHint': 'Category',
      'expense': 'Expense',
      'generalCategory': 'General',
      'manageFinancesAndExpenses': 'Finances & Expenses',
      'revenue': 'Revenue',
      'attendanceCalendar': 'Attendance Calendar',
      'personalInfo': 'Personal Info',
      'nationalId': 'National ID',
      'notProvided': 'Not provided',
      'noLinkedAccount': 'This player has no linked account yet, so attendance history is not available',
      'totalAttendanceDays': 'Total attendance days',
      'presentStatus': 'Present',
      'absentStatus': 'Absent',
      'todayStatus': 'Today',
      'futureStatus': 'Upcoming',
      'viewAttendance': 'View attendance',
    },
    'ar': {
      'appName': 'نظام إدارة الأكاديميات الرياضية',
      'workspace': 'مساحة العمل',
      'workspacesTitle': 'مساحات العمل',
      'basicSection': 'الأساسية',
      'managementSection': 'الإدارة',
      'switchWorkspace': 'تبديل مساحة العمل',
      'createAcademy': 'إنشاء أكاديمية جديدة',
      'academyName': 'اسم الأكاديمية',
      'academyType': 'نوع الأكاديمية',
      'sport': 'الرياضة',
      'logo': 'شعار الأكاديمية',
      'branchesAndGroups': 'الفروع والمجموعات',
      'profile': 'الملف الشخصي',
      'invitations': 'الدعوات',
      'pendingInvitationsTitle': 'الدعوات المعلقة',
      'players': 'اللاعبون',
      'publicPlayersList': 'قائمة اللاعبين العامة',
      'manageAllPlayersTitle': 'إدارة جميع اللاعبين',
      'packagesAndSubscriptions': 'الباقات والاشتراكات',
      'choosePackageTitle': 'اختر باقة الأكاديمية',
      'choosePackageDesc': 'اختر باقة الأكاديمية (Free / Pro)',
      'userManagement': 'إدارة المستخدمين',
      'noUsersRegistered': 'لا يوجد مستخدمون',
      'activityLog': 'سجل نشاط الأكاديمية',
      'activityLogDesc': 'سجل نشاط الأكاديمية والعمليات',
      'subscriptionReports': 'تقارير الاشتراكات',
      'otherRevenueReport': 'تقرير الإيرادات الأخرى',
      'employeeAttendanceAndSalaries': 'حضور ورواتب الموظفين',
      'otherExpenses': 'المصروفات الأخرى',
      'deleteAccount': 'حذف الحساب',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'changeLanguage': 'تغيير اللغة',
      'aboutApp': 'عن التطبيق',
      'aboutAppAndPolicies': 'حول التطبيق والسياسات',
      'aboutAppPlaceholderDesc': 'سياسة الخصوصية والشروط والأحكام',
      'noBranchesYet': 'لا توجد فروع بعد',
      'addBranch': 'إضافة فرع',
      'noPendingInvitations': 'لا توجد دعوات معلقة',
      'inviteUser': 'دعوة مستخدم',
      'noPlayersRegistered': 'لا يوجد لاعبون مسجلون',
      'addPlayer': 'إضافة لاعب',
      'searchPlayers': 'البحث عن لاعبين...',
      'currentSubscription': 'الاشتراك الحالي',
      'freePlan': 'باقة Free',
      'upgrade': 'ترقية',
      'normalUser': 'مستخدم عادي',
      'administrator': 'مدير / مسؤول',
      'saveChanges': 'حفظ التغييرات',
      'editProfile': 'تعديل الملف الشخصي',
      'changePassword': 'تغيير كلمة المرور',
      'oldPassword': 'كلمة المرور الحالية',
      'newPassword': 'كلمة المرور الجديدة',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmChange': 'تأكيد التغيير',
      'deleteConfirmationTitle': 'حذف الحساب؟',
      'deleteConfirmationDesc': 'هذا الإجراء نهائي ولا يمكن التراجع عنه. هل أنت متأكد من رغبتك في حذف الحساب نهائياً؟',
      'cancel': 'إلغاء',
      'confirmDelete': 'حذف نهائياً',
      'privacyPolicy': 'سياسة الخصوصية',
      'termsAndConditions': 'الشروط والأحكام',
      'contactUs': 'اتصل بنا',
      'version': 'الإصدار',
      'noRevenueRecords': 'لا توجد سجلات إيرادات',
      'noExpenses': 'لا توجد مصروفات مسجلة',
      'noEmployees': 'لا يوجد موظفون',
      'noActivity': 'لا يوجد نشاط مسجل',
      'role': 'الدور',
      'actions': 'الإجراءات',
      'status': 'الحالة',
      'date': 'التاريخ',
      'amount': 'المبلغ',
      'category': 'الفئة',
      'categoryExampleHint': 'الفئة (مثل: صيانة، أدوات)',
      'attendance': 'الحضور',
      'salaries': 'الرواتب',
      'present': 'حاضر',
      'absent': 'غائب',
      'late': 'متأخر',
      'leave': 'إجازة',
      // شاشة اللاعبين
      'manageSubscribersAndSports': 'إدارة المشتركين والرياضات',
      'noSubscribersYet': 'لا يوجد مشتركون حالياً',
      'expiresOn': 'ينتهي في',
      'currency': 'ج.م',
      'addNewSubscriptionTitle': 'إضافة اشتراك مشترك جديد',
      'subscriberName': 'اسم المشترك',
      'sportExampleHint': 'الرياضة (مثل: كرة قدم)',
      'subscriptionAmount': 'قيمة الاشتراك',
      'addAndSave': 'إضافة وحفظ',
      'general': 'عام',
      // شاشة المصروفات
      'financeAndExpensesManagement': 'إدارة المالية والمصروفات',
      'income': 'الإيرادات',
      'expenses': 'المصروفات',
      'netBalance': 'الصافي',
      'noTransactionsRecorded': 'لا توجد حركات مالية مسجلة',
      'addNewTransaction': 'إضافة حركة مالية جديدة',
      'descriptionLabel': 'البيان / الوصف',
      'transactionType': 'نوع الحركة:',
      'incomeType': 'إيراد',
      'expenseType': 'مصروف',
      'save': 'حفظ',
      // شاشة الملف الشخصي
      'fullName': 'الاسم بالكامل',
      'phoneNumber': 'رقم الهاتف',
      'nameRequired': 'الاسم مطلوب',
      'phoneRequired': 'رقم الهاتف مطلوب',
      'phoneIncomplete': 'رقم الهاتف غير مكتمل',
      'academyNameRequired': 'اسم الأكاديمية مطلوب',
      'profileSavedSuccess': 'تم حفظ التغييرات بنجاح',
      'avatarChangeComingSoon': 'تغيير الصورة الشخصية قريباً',
      'requiredField': 'مطلوب',
      'minSixChars': 'يجب ألا تقل عن 6 أحرف',
      'passwordsMismatch': 'كلمتا المرور غير متطابقتين',
      'passwordChangedSuccess': 'تم تغيير كلمة المرور بنجاح',
      'genericError': 'حدث خطأ، حاول مرة أخرى',
      'sportFootball': 'كرة القدم',
      'sportBasketball': 'كرة السلة',
      'sportVolleyball': 'كرة الطائرة',
      'sportSwimming': 'السباحة',
      'sportTennis': 'التنس',
      'sportOther': 'أخرى',
      'notLoggedIn': 'غير مسجل دخول',
      // تبديل مساحة العمل
      'noAcademyNameYet': 'لا يوجد اسم أكاديمية بعد',
      'chooseWorkspace': 'اختر مساحة العمل',
      'noOtherAccountsOnDevice': 'لا توجد حسابات أخرى مسجّلة على هذا الجهاز',
      'switchedTo': 'تم التبديل إلى',
      'projectManager': 'مدير مشروع',
      'member': 'عضو',
      // شاشات الدخول والتسجيل
      'welcomeBack': 'مرحباً بعودتك',
      'loginSubtitle': 'سجّل الدخول لإدارة أكاديميتك الرياضية',
      'emailLabel': 'البريد الإلكتروني',
      'passwordLabel': 'كلمة المرور',
      'enterEmail': 'يرجى إدخال البريد الإلكتروني',
      'invalidEmailFormat': 'صيغة البريد الإلكتروني غير صحيحة',
      'enterPassword': 'يرجى إدخال كلمة المرور',
      'passwordMinLength': 'كلمة المرور يجب ألا تقل عن 6 أحرف',
      'forgotPassword': 'نسيت كلمة المرور؟',
      'contactSupportForPassword': 'يرجى التواصل مع الدعم لاستعادة كلمة المرور',
      'resetPasswordTitle': 'إعادة تعيين كلمة المرور',
      'resetPasswordDesc': 'أدخل البريد الإلكتروني المسجل بحسابك وسنرسل لك رابطًا لإعادة تعيين كلمة المرور.',
      'sendResetLink': 'إرسال رابط إعادة التعيين',
      'resetLinkSentTitle': 'راجع بريدك الإلكتروني',
      'resetLinkSentDesc': 'أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني. افتحه واتبع التعليمات لتعيين كلمة مرور جديدة.',
      'backToLogin': 'العودة لتسجيل الدخول',
      'tooManyRequests': 'محاولات كثيرة جدًا، حاول مرة أخرى لاحقًا',
      'networkError': 'خطأ في الاتصال، يرجى التحقق من الإنترنت',
      'accountDisabled': 'تم تعطيل هذا الحساب',
      'verifyEmailBanner': 'يرجى تفعيل بريدك الإلكتروني',
      'verifyEmailBannerDesc': 'أرسلنا رابط تفعيل إلى بريدك الإلكتروني.',
      'resendVerificationEmail': 'إعادة إرسال رابط التفعيل',
      'verificationEmailSent': 'تم إرسال رابط التفعيل',
      'iVerifiedRefresh': 'قمت بالتفعيل، تحديث',
      'loginButton': 'تسجيل الدخول',
      'or': 'أو',
      'noAccountYet': 'ليس لديك حساب؟',
      'createNewAccount': 'إنشاء حساب جديد',
      'registerSubtitle': 'انضم الآن وابدأ إدارة أكاديميتك الرياضية',
      'enterFullName': 'أدخل اسمك الكامل',
      'enterName': 'يرجى إدخال الاسم',
      'nameTooShort': 'الاسم قصير جداً',
      'confirmPasswordRequired': 'يرجى تأكيد كلمة المرور',
      'createAccountButton': 'إنشاء الحساب',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟',
      'iAmManager': 'أنا من المسؤولين (مانيجر)',
      'managerAccessCode': 'كود تفعيل المدير',
      'managerAccessCodeHint': 'أدخل كود تفعيل المدير',
      'managerCodeRequired': 'يرجى إدخال كود تفعيل المدير',
      'managerRoleHint': 'اسأل مسؤول الأكاديمية عن الكود لو مش موجود عندك',
      // الفروع
      'addBranchTitle': 'إضافة فرع جديد',
      'branchName': 'اسم الفرع',
      'branchNameRequired': 'اسم الفرع مطلوب',
      'branchAddress': 'العنوان (اختياري)',
      'branchAdded': 'تمت إضافة الفرع بنجاح',
      'deleteBranchConfirm': 'حذف هذا الفرع؟',
      'managersOnlyHint': 'إضافة الفروع متاحة فقط لمدير الأكاديمية',
      // شاشة الباقات
      'choosePackageHeading': 'اختر باقة الأكاديمية',
      'choosePackageSubheading': 'نوفر عدة خيارات تناسب احتياجاتك',
      'current': 'الحالي',
      'free': 'مجاني',
      'proPackage': 'باقة Pro',
      'suitableForMediumAcademies': 'مناسبة للأكاديميات المتوسطة',
      'perMonth': '/ شهريًا',
      'currentSubscriptionButton': 'اشتراكك الحالي',
      'subscribeNow': 'اشترك الآن',
      'oneBranch': 'فرع واحد',
      'twoGroups': 'مجموعتان',
      'upTo50Players': '50 لاعبًا',
      'upTo50Reports': '50 تقريرًا',
      'twoBranches': 'فرعان',
      'upTo10Groups': 'حتى 10 مجموعات',
      'upTo200Players': 'حتى 200 لاعب',
      'upTo200ReportsMonthly': 'حتى 200 تقرير شهريًا',
      'prioritySupport': 'دعم فني ذو أولوية',
      'comingSoonFeature': 'قريباً',
      // محتوى حول التطبيق
      'aboutAppBody': 'نظام إدارة الأكاديميات الرياضية بيساعد أصحاب الأكاديميات والمدربين يديروا الفروع واللاعبين والاشتراكات والمالية والموظفين من مكان واحد، ببساطة وكفاءة.',
      'ourFeatures': 'مميزات التطبيق',
      'featureBranches': 'إدارة عدة فروع ومجموعات',
      'featurePlayers': 'قاعدة بيانات كاملة للاعبين والمشتركين',
      'featureFinance': 'متابعة الإيرادات والمصروفات والتقارير',
      'featureAttendance': 'تسجيل حضور اللاعبين عن طريق كود QR',
      'featureTeam': 'إدارة أدوار وصلاحيات فريق العمل',
      'developedBy': 'تم تطويره باهتمام خاص للأكاديميات الرياضية',
      // بحث وترتيب وحضور اللاعبين
      'searchByPlayerName': 'ابحث عن لاعب',
      'sortByName': 'ترتيب بالاسم',
      'printList': 'طباعة القائمة',
      'printPreviewTitle': 'معاينة قائمة اللاعبين',
      'copyText': 'نسخ',
      'textCopied': 'تم النسخ',
      'scanAttendance': 'تسجيل حضور بالباركود',
      'showQrCode': 'عرض كود QR',
      'playerQrCode': 'كود QR الخاص باللاعب',
      'close': 'إغلاق',
      'pointCameraAtCode': 'وجّه الكاميرا نحو كود QR الخاص باللاعب',
      'attendanceRecorded': 'تم تسجيل حضور',
      'alreadyCheckedInToday': 'مسجل حضوره بالفعل اليوم',
      'codeNotRecognized': 'الكود غير معروف — هذا اللاعب غير مسجل',
      'manualCodeEntry': 'أو أدخل الكود يدوياً',
      'submitCode': 'إرسال',
      // اختيار الدور عند التسجيل
      'accountType': 'نوع الحساب',
      'roleManager': 'مانيجر',
      'roleEmployee': 'موظف',
      'roleCoach': 'متدرب (عادي)',
      'roleManagerDesc': 'كل الصلاحيات + تسجيل حضور الموظفين',
      'roleEmployeeDesc': 'صلاحيات عادية + تسجيل حضور المتدربين',
      'roleCoachDesc': 'صلاحيات عادية',
      // حضور الموظفين (يسجّله المدير)
      'employeeAttendanceTitle': 'حضور الموظفين',
      'scanEmployeeAttendance': 'تسجيل حضور موظف',
      'noEmployeesRegisteredYet': 'لا يوجد موظفون مسجلون بعد',
      'checkedInToday': 'حضر اليوم',
      'notCheckedInToday': 'لم يحضر اليوم',
      'pointCameraAtEmployeeCode': 'وجّه الكاميرا نحو كود QR الخاص بالموظف',
      'employeeNotRecognized': 'الكود غير معروف — هذا الموظف غير مسجل',
      'myQrCode': 'كود QR الخاص بي',
      'myQrCodeHint': 'اعرض هذا الكود عشان يتسجل حضورك',
      // حول التطبيق / التواصل / القانوني
      'editContactNumber': 'تعديل رقم التواصل',
      'contactNumberLabel': 'رقم التواصل',
      'contactNumberSaved': 'تم تحديث رقم التواصل',
      'termsAndConditionsTitle': 'الشروط والأحكام',
      'privacyPolicyTitle': 'سياسة الخصوصية',
      'contactUsTitle': 'اتصل بنا',
      'toggleTheme': 'تبديل الوضع الفاتح / الداكن',
      'lightDarkMode': 'الوضع الفاتح / الداكن',
      'darkModeLabel': 'الوضع الداكن',
      'lightModeLabel': 'الوضع الفاتح',
      // الدعوات
      'sendInvitationTitle': 'إرسال دعوة',
      'invitationEmailHint': 'البريد الإلكتروني الخاص بالمدعو',
      'inviteeRoleLabel': 'دور المدعو',
      'invitationSentSuccess': 'تم إرسال الدعوة بنجاح',
      'invitationsManagersOnlyHint': 'إرسال الدعوات متاح فقط لمدير الأكاديمية',
      'invitedAsHint': 'هذا البريد مدعو للانضمام كـ',
      'sentOnLabel': 'تم الإرسال في',
      // رسائل خطأ الدخول/التسجيل
      'enterValidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
      'noAccountWithEmail': 'لا يوجد حساب مسجّل بهذا البريد الإلكتروني',
      'incorrectPassword': 'كلمة المرور غير صحيحة',
      'emailAlreadyRegistered': 'هذا البريد الإلكتروني مسجّل بالفعل، جرّب تسجيل الدخول',
      'invalidManagerCode': 'كود تفعيل المدير غير صحيح',
      'incorrectCurrentPassword': 'كلمة المرور الحالية غير صحيحة',
      // إدارة الاشتراكات (المدير)
      'manageSubscriptionsTitle': 'إدارة الاشتراكات',
      'manageSubscriptionsDesc': 'ابحث عن مستخدم بالبريد الإلكتروني لإنشاء أو مراجعة اشتراكه',
      'searchUserByEmailLabel': 'البحث عن مستخدم بالبريد الإلكتروني',
      'searchUserByEmailHint': 'user@gmail.com',
      'searchButton': 'بحث',
      'userNotFoundMsg': 'لا يوجد مستخدم بهذا البريد الإلكتروني',
      'selectedUserLabel': 'المستخدم المحدد',
      'subscriptionDurationLabel': 'المدة',
      'duration1Month': 'شهر واحد',
      'duration3Months': '3 أشهر',
      'duration6Months': '6 أشهر',
      'duration1Year': 'سنة واحدة',
      'amountPaidLabel': 'المبلغ المدفوع',
      'amountPaidHint': 'أدخل المبلغ',
      'expiryDatePreviewLabel': 'تاريخ الانتهاء',
      'createSubscriptionButton': 'إنشاء الاشتراك',
      'subscriptionCreatedSuccess': 'تم إنشاء الاشتراك بنجاح',
      'subscriptionCreationFailed': 'فشل إنشاء الاشتراك',
      'subscriptionHistoryTitle': 'سجل الاشتراكات',
      'noSubscriptionHistory': 'لا يوجد سجل اشتراكات حتى الآن',
      'statusActive': 'نشط',
      'statusExpired': 'منتهي',
      'mySubscriptionTitle': 'اشتراكي',
      'noActiveSubscriptionMsg': 'ليس لديك اشتراك حتى الآن',
      'contactAdminToRenewMsg': 'يرجى التواصل مع الإدارة لتفعيل أو تجديد اشتراكك.',
      'startDateLabel': 'تاريخ البداية',
      'expiryDateLabel': 'تاريخ الانتهاء',
      'amountPaidColumnLabel': 'المبلغ المدفوع',
      'pleaseEnterValidAmount': 'يرجى إدخال مبلغ صحيح',
      'pleaseSearchUserFirst': 'يرجى البحث عن مستخدم وتحديده أولاً',
      'football': 'كرة القدم',
      'manageButton': 'إدارة',
      'viewButton': 'عرض',
      'noSubscriptionShort': 'لا يوجد اشتراك',
      'currentRoleLabel': 'الدور الحالي',
      'promoteToEmployeeButton': 'ترقية إلى موظف',
      'revertToUserButton': 'إعادته إلى مستخدم عادي',
      'roleUpdatedSuccess': 'تم تحديث الدور بنجاح',
      'roleUpdateFailed': 'فشل تحديث الدور',
      'avatarUploadCorsError': 'فشل رفع الصورة: تعذر التأكد من الصورة بعد الرفع. غالبًا السبب أن إعدادات CORS غير مفعّلة على Firebase Storage لهذا التطبيق (نسخة الويب) — اطلب من المطور تفعيل CORS على الـ Bucket، أو جرّب من تطبيق الموبايل.',
      'avatarUploadPermissionError': 'ليس لديك صلاحية لرفع هذه الصورة.',
      'avatarUploadGenericError': 'فشل رفع الصورة. حاول مرة أخرى.',
      'performedByLabel': 'بواسطة',
      'searchUsersHint': 'ابحث بالاسم أو البريد الإلكتروني أو الهاتف',
      'noUsersFound': 'لا يوجد مستخدمون',
      'totalRevenueLabel': 'إجمالي الإيرادات',
      'revenueByCategoryLabel': 'الإيرادات حسب الفئة',
      'revenueTransactionsLabel': 'حركات الإيرادات',
      'nationalIdLabel': 'الرقم القومي',
      'nationalIdHint': 'الرقم القومي (14 رقم)',
      'nationalIdInvalid': 'الرقم القومي يجب أن يكون 14 رقمًا',
      'copiedToClipboard': 'تم النسخ',
      'copyCode': 'نسخ الكود',
      'camera': 'الكاميرا',
      'gallery': 'المعرض',
      'categoryHint': 'الفئة',
      'expense': 'مصروف',
      'generalCategory': 'عام',
      'manageFinancesAndExpenses': 'الماليات والمصروفات',
      'revenue': 'الإيرادات',
      'attendanceCalendar': 'تقويم الحضور',
      'personalInfo': 'البيانات الشخصية',
      'nationalId': 'الرقم القومي',
      'notProvided': 'غير متوفر',
      'noLinkedAccount': 'هذا الشخص ليس له حساب مرتبط بعد، لذلك سجل الحضور غير متاح',
      'totalAttendanceDays': 'إجمالي أيام الحضور',
      'presentStatus': 'حاضر',
      'absentStatus': 'غائب',
      'todayStatus': 'اليوم',
      'futureStatus': 'قادم',
      'viewAttendance': 'عرض الحضور',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}